name: FTP Deployment

on:
  push:
    branches: [master] # replace with your master branch name
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: crysta.online # replace with your server name
        username: ${{ secrets.FTP_USERNAME }} # store your FTP username in secrets
        password: ${{ secrets.FTP_PASSWORD }} # store your FTP password in secrets
