name: FTP Deployment

on:
  push:
    branches: [master] # replace with your master branch name
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.crysta.online # use your FTP server hostname
        username: carwash@crysta.online # use your FTP username
        password: ${{ secrets.FTP_PASSWORD }} # use your FTP password secret
        server-dir: /home/crystaon/public_html/carwash # use the desired server directory
        local-dir: ./ # replace with the directory of the files you want to upload
        args: -p 21 --explicit --delete # use explicit FTPS and add --explicit argument
